### ISSUE TITLE
We need the ArticleTracker table (and data) pushed to Stage and Production

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#104]
@lhorne-gavant 

When we push data to Stage and Production, we need to push the articletracker table, which the build process adds to (in the Development database, I presume).  This table is used in the WhatsNew function to keep track of articles when they first appear in the database, versus when they are modified (e.g., just edited).  

What's New from the Server now returns only a list of those issues that are actually new, not those that may have changed.  But it depends (at run time, each time) on checking the articleTracker table to be able tell the difference between a revision and a new article.

I just copied them over manually so Stage and Production would work right based on the last data update.

**Comment by lhorne-gavant** [comment]
@nrshapiro 
I've updated the data migration utility to push the article_tracker table to staging and production like we do for api_biblioxml and api_articles.
