### ISSUE TITLE
Downloads blocked for Federation (?) users and possibly others

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#105]
@lhorne-gavant 

Some users (including Tuckett) are having trouble using the download document feature from the client.  I have not seen that otherwise, but it turns out it depends on how you login.  I used the spoofing feature of PaDS to login as him with the account he was having trouble with, and I replicated the problem.

Looking at the Developer console in Google shows the problem:

```
/browse/document/CJP.018.0141A?page=P0141:1 Mixed Content: The site at 'https://pep-web.rocks/' was loaded over a secure connection, but the file at 'https://api.pep-web.rocks/v2/Documents/Downloads/PDF/CJP.018.0141A/?client-id=2&client-session=a8f72bbb-243d-4c24-afff-9797af5067b6' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
pep-07519fe97221854f2ca9e562727dc998.js:1068 Unsafe attempt to load URL http://peparchive.org/pepa1dtd/pepkbd3.dtd from frame with URL https://pep-web.rocks/browse/document/CJP.018.0306A?page=P0141. Domains, protocols and ports must match.
```
Unfortunately, all I'm doing from Python to return the file is using a FileResponse call, and I've yet to understand why it would use HTTP rather than HTTPS, which is what the client connection to the server is.  

This is the relevant code:
```
                   if flex_fs.key is not None:                    # S3
                        fileurl = flex_fs.fs.url(filename)
                        filename = wget.download(fileurl)

                    stamped_file = opasPDFStampCpyrght.stampcopyright(user_name, input_file=filename)
                    response.status_code = httpCodes.HTTP_200_OK
                    ret_val = FileResponse(path=stamped_file,
                                           status_code=response.status_code,
                                           filename=os.path.split(stamped_file)[1], 
                                           media_type=media_type)
```

Leyla, do you know how to get around this?  I did ask on the gitter for FastAPI just now.  Note that fileresponse is actually provided by the Starlette library.

The [Google page about the error](https://blog.chromium.org/2020/02/protecting-users-from-insecure.html) does say this:
```
Enterprise and education customers can disable blocking on a per-site basis via the existing InsecureContentAllowedForUrls policy by adding a pattern matching the page requesting the download. 

In the future, we expect to further restrict insecure downloads in Chrome. We encourage developers to fully migrate to HTTPS to avoid future restrictions and fully protect their users. Developers with questions are welcome to email us at security-dev@chromium.org. 

Posted by Joe DeBlasio, Chrome Security team
```

So perhaps that something you can set?

Another option would be for me to return the downloads as binary objects to the client, or the S3 address for PDFOriginals, and then the client itself can download to the user's system.

Or I'm open to other ideas, especially any straightforward fixes.

Note: when I log in as me, using https, it works fine.

**Comment by nrshapiro** [comment]
@adistasio @lhorne-gavant 

Comments on my options above regarding this?  DT is relieved I know what's wrong, but I still don't know what we can (and should) do to fix it. 

Thanks.

**Comment by lhorne-gavant** [comment]
@nrshapiro 
I took a look at the requests and noticed that the web client was making a request to the api but the api requires trailing forward slashes so it was redirecting the client to a url with the trailing slash after the document ID, but without https. The ELB was then redirecting requests back to https. 

1. GET `https://stage-api.pep-web.rocks/v2/Documents/Downloads/PDFORIG/CJP.018.0141A?client-id=.......`
2. API redirects to GET `http://stage-api.pep-web.rocks/v2/Documents/Downloads/PDFORIG/CJP.018.0141A/?client-id=.......`
3. ELB redirects back to https with `https://stage-api.pep-web.rocks/v2/Documents/Downloads/PDFORIG/CJP.018.0141A/?client-id=.......`

The redirect to an http url was causing issues. I've asked Adam to make sure there is a trailing slash after document ID and the issue seems to be resolved on staging now.

**Comment by nrshapiro** [comment]
@lhorne-gavant  Great, thanks!  It appears to work now on stage when I spoof the users reporting problems.  Final test is in their hands.  

Wouldn't it be a good idea for Adam to add the trailing slash to other calls if they are being similarly redirected to HTTP, either from a security perspective or response times?

**Comment by lhorne-gavant** [comment]
@nrshapiro 
Just fyi this change hasn't been deployed to production yet. 
Adam should already be adding the trailing slash to other calls but if you run into this issue again let us know.
