### ISSUE TITLE
Need DevOPS routine to Push Settings

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#126]
We need a way, similar to running the other build process, to push settings from Stage to Production.

run-push-admin-to-prod.txt

And there's a program for that in the project

opasPushSettingsToProduction.py

No arguments are needed...but for testing, you can use:

opasPushSettingsToProduction.py -p

which will print messages to console but not "push" anything.

This has been used a number of times from my local system.  Let me know if you have any problems running online.

You might need some additional items in localsecrets, it should be in any I sent since Mar 2021:

(added 2021-03-21 to allow copying settings from stage to production)

STAGE_DB_HOST 
PRODUCTION_DB_HOST 
STAGE2PROD_PW 
STAGE2PROD_USER

**Comment by lhorne-gavant** [comment]
The deployment process should now accept the ‘run-push-admin-to-prod.txt’ file. Let me know if you run into any issues.
