### ISSUE TITLE
PDF/EPub conversions - to include active links to references

### ISSUE THREAD

**Issue by SophieMBennett** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#139]
Transferred from Support thread re: https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/179

**Comment by nrshapiro** [comment]
This is implemented for both epubs and pdfs in Server version [2022.0510/v2.1.154] and afterwards.

Not yet pushed to production.

Same as #162
