### ISSUE TITLE
Articles (and artstat) Database tables not Cleared on Full rebuild

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#160]
When a full-rebuild is run, the database article and artstat tables as well as the solr cores should be cleared.  I don't think the current scripts/process does this, at least for the database.  I notice old test files still in the articles table from a long time ago, and I don't see those files on S3, so they are not being re-added.

The first call to opasDataLoader should do a clear using the --resetcore option.  The solr cores and the database article and artstat tables will be cleared.  You need to also use option --nocheck or the program will prompt for confirmation on the clear.  I note the help should mention the database tables and it does not (it mentions it when you specify the option as part of the confirmation).  You also need to make sure that the first process has finished doing that before running others.  Running the option with the shortest build type (PEPFree) first, should make that easy, allowing it to finish before the other start.

Please make sure the AWS script for run-full-rebuild.txt clears the tables before the build using these options.

**Comment by lhorne-gavant** [comment]
@nrshapiro I'll work on getting the artstat table added to the deployment process this week, along with the other pending items.
