### ISSUE TITLE
Database Full Rebuild -- Bibliography Linking Issues

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#174]
The new opasDataLoader xmlProcessing module, which compiles from KBD3 to EXP_ARCH1, uses the api_articles table and solr docs core to cross-link articles in PEP-Web, but when doing a full rebuild at the start of the year (like now), those are cleared before processing, so the xml compile can't use that method during the build.  That can be remedied fairly easily, but further, linking is not as nearly good as it was before, and there's no persistent link override option as we had before.  All the current all-in-one processing  using --rebuild and the way it runs on AWS is extremely slow, which isn't a major issue, but is prohibitive when trying to QA, adjust, and rebuild.

So I'm thinking about a potentially better process flow centered around a once-again persistent bibliography table:

- Phase I: Initial Full Rebuild
- Phase II: Incremental enhancement (can be repeated anytime throughout the year)
- Phase III: Deep Link Enhancement

**Phase I: Initial Full Rebuild**
1) Turn off the clearing of these two RDS tables when doing a full build.  If that's done, old removed records would linger, but I do have a fairly new opasDataCleaner module developed for other needs which goes through and compares records to the file system removing any records where the file has been removed.  That would need to be added to the process flow after the build, and/or as a separate "regular" cleaning process since these tables impact statistics.

2) The opasDataLoader module could use the now "preserved" api_biblioxml table which would store rx (known) and rxcf (possible) links as the main source of linking
a) a new biblio entry would be linked via the default linking, based on the regex model and what's tagged in the reference., and the links written to the new database entry
b) an existing biblio entry would use what's in the database.  That provides the link override mechanism we had before, since this table can be manually edited when errant links are discovered or as part of a QA process  
c) any attempt at deeper link checks would be removed from this phase, speeding up the process.

3) After an opasDataLoader run, opasDataCleaner would need to be run.

**Phase II: Incremental enhancement (can be repeated anytime throughout the year)**
1) The api_biblioxml table can be manually QA'd, and links updated manually.  

2) The opasDataLoader would have a --linkupdate option added such that it would go through the api_biblioxml table based on date of update (or an updated flag) in the  table, recompile and reload any files that are flagged as relinked.

**Phase III: Deep Link Enhancement**
1) A separate opasDataLinker module would be developed which is focused on "deep checking" links based a) the previous deeper comparison rules via Solr and MySQL similarity or later b) AI processing.  As the result of a pass, it would update the api_biblioxml table and flag changed entries. It would have two modes: --checkunlinked (default) or --checkall.  This could benefit later from AI enhancements.  I have a small prototype of this I'm experimenting with based on the old code.
2) After the opasDataLinker is run, opasDataLoader would be run with the --linkupdate option

cc: @rickardnyman @jordanallen-dev @ocappello

**Comment by nrshapiro** [comment]
@jordanallen-dev 

One other change that will possibly be needed: the initial rebuild phase last week was terminated by the system after 24 hours (either AWS or in the DevOps configured pipelines).  Rebuilding all the XML takes time, and it may still take more than 24 hours after the changes above.  We'll see, but it might be good to find where that is configured.

**Comment by nrshapiro** [comment]
cc: @rickardnyman @jordanallen-dev @ocappello @davidtuckett 
Status updated in context:

> The new opasDataLoader xmlProcessing module, which compiles from KBD3 to EXP_ARCH1, uses the api_articles table and solr docs core to cross-link articles in PEP-Web, but when doing a full rebuild at the start of the year (like now), those are cleared before processing, so the xml compile can't use that method during the build. That can be remedied fairly easily, but further, linking is not as nearly good as it was before, and there's no persistent link override option as we had before. All the current all-in-one processing using --rebuild and the way it runs on AWS is extremely slow, which isn't a major issue, but is prohibitive when trying to QA, adjust, and rebuild.
> 
> So I'm thinking about a potentially better process flow centered around a once-again persistent bibliography table:
> 
> * Phase I: Initial Full Rebuild
> * Phase II: Incremental enhancement (can be repeated anytime throughout the year)
> * Phase III: Deep Link Enhancement
> 
> **Phase I: Initial Full Rebuild**
> 
> 1. Turn off the clearing of these two RDS tables when doing a full build.     

 **[Done]** **[On AWS]**

> If that's done, old removed records would linger, but I do have a fairly new opasDataCleaner module developed for other needs which goes through and compares records to the file system removing any records where the file has been removed.  That would need to be added to the process flow after the build, and/or as a separate "regular" cleaning process since these tables impact statistics.
> 2. The opasDataLoader module could use the now "preserved" api_biblioxml table which would store rx (known) and rxcf (possible) links as the main source of linking 
>    a) a new biblio entry would be linked via the default linking, based on the regex model and what's tagged in the reference., and the links written to the new database entry     
  
**[Done]** Build not ready for AWS yet

>    b) an existing biblio entry would use what's in the database.  That provides the link override mechanism we had before, since this table can be manually edited when errant links are discovered or as part of a QA process 

**[Done]** Build not ready for AWS yet

>    c) any attempt at deeper link checks would be removed from this phase, speeding up the process. 

**[Done]** Build not ready for AWS yet

> 3. After an opasDataLoader run, opasDataCleaner would need to be run. 
> 
> **Phase II: Incremental enhancement (can be repeated anytime throughout the year)**
> 
> 1. The api_biblioxml table can be manually QA'd, and links updated manually. 
This works well (it's what I've traditionally done), but also allows detecting patterns of errors and linking problems.  For example, I noted that the links we'd coded for various books "broke" when we split books and changed the id of the main instance.  As part of this fix, I also noted that a lot of references miss the start page number by 1.  The opasDataLinker module now has a function which checks the page before the cited page in the reference, if the cited page doesn't exist in the system as an id., and fixes it in the biblioxml table, which then fixes it in the database the next load.

> 2. The opasDataLoader would have a --linkupdate option added such that it would go through the api_biblioxml table based on date of update (or an updated flag) in the  table, recompile and reload any files that are flagged as relinked.
Instead, I made the opasDataLoader check the biblioxml table for updates by default.  

**_New TBD: I will add a check so that no bad link can go in the actual Solr load._**

> 
> **Phase III: Deep Link Enhancement**
> 
> 1. A separate opasDataLinker module would be developed which is focused on "deep checking" links based a) the previous deeper comparison rules via Solr and MySQL similarity or later b) AI processing.  As the result of a pass, it would update the api_biblioxml table and flag changed entries. It would have two modes: --checkunlinked (default) or --checkall.  This could benefit later from AI enhancements.  I have a small prototype of this I'm experimenting with based on the old code.

_** In Progress**_ 

> 2. After the opasDataLinker is run, opasDataLoader would be run with the --linkupdate option
> 
As noted above, opasDataLoader now checks automatically.  Will watch to make sure it is acceptably efficient to do so (I've not run this on AWS yet).

Trying to decide where to put OpasDataLinker in the pipelines.   
 a) Running it at the start of each update would make the update one step, but wouldn't fix any new items added during the update
 b) Running it at the end would fix everything, but then you'd need to do another update to have them put in place.

Will see when it's done what's best.

**Comment by nrshapiro** [comment]
@jordanallen-dev @ocappello @davidtuckett

Good progress on opasDataLinker.  

I'm still working on checking for outlying cases and refining the rules.  In fact I'm still running the linker--it hasn't yet finished a full run of the data.  There are 1.6 million bibliographic references in PEP-Web!

I'm refining the command line options to make it most useful as we run it in the pipelines and as I run it manually to test and fill in references.

When we get the build process on AWS fixed, I'm move it to stage for more testing.  I don't want to put it up before then because I'm making changes to the schema and I don't want potentially two factors affecting the pipeline builds which aren't working now anyway.

As long as someone has the ability to check and edit the table, you can tweak references, remove any false links reported, add important links if they are missing.  This is something I have done for years in the old system and will continue with the new system at least in the near term.

For the client, there's an important change to the way links will appear in the XML.

The main reference rx link is the same.  

The rxcf link will now be either empty or a list of "possible" and "related" references, in rxcf_confidence order.  Since there's more than one, the rxcf_confidence field will just show the max, but each rx article ID in rxcf will have the confidence (floating point numbers from 0 to 1) appended to it prefixed by ":", e.g.,

`<be label="6" id="B006" rx="ZBK.072.0000A" rxconf="0.91" rxcf="ZBK.072.0000A:0.99, ZBK.072.0001A:0.99, ZBK.072.0048A:0.75, ZBK.072.0022A:0.71, PAQ.058.0526A:0.69" rxcfconf="0.99"><a><l>Hartman</l>, Heinz</a>: <t>“Ego Psychology and the Problem of Adaptation”,</t> in <bsa><a><l>Rapaport</l>, David</a></bsa>: <bst>“Organization and Pathology of Thought”</bst>, <bp>Columbia University Press</bp>, N.Y. <bpd>1951</bpd></be>`

Note the rx value is ALSO in the rxcf list.  At first I excluded this, but later decided that it made it much easier to edit the api_biblioxml table to remove a false positive link from rx.  Since the false positive is now listed in rxcf, you can just remove the rx value and it's rx_confidence from the table, but the link to the "false positive", which is almost always a related article, is already in the related article list so you don't have to add it, as you would if I left it out.

**Comment by nrshapiro** [comment]
@jordanallen-dev @ocappello @davidtuckett

From the above, what we need added to the client to handle this, like the old GVPi system, is to have a way for the user to get to these: e.g., for it to show the potential / related references in a hover popup, and let the user pick one.

Note in the example I placed in the post above, there's a value in both rx and rxcf, but for heuristic matches, you may only have rxcf values, making the linking feature in the client essential to add soon.

**Comment by davidtuckett** [comment]
Agreed important as per meeting just now.

**Comment by nrshapiro** [comment]
I'm working on how to integrate the data linker into the build process.

**Nightly builds.**
1) Regular build process
2) At the end, start opasDataLinker with the option:
`opasDataLinker --nightly`
This will look at references from articles added in the past day, and do any link changes to api_biblioxml

The next day, when the nightly build runs using the --smartload option of opasDataLoader, any file where linking was changed in the api_biblioxml table will be updated.  That includes any files which had links manually changed as per data manager review (should be done occasionally) or per data manager manual fixes to links in the table per user reports.

**Rebuilds, when new journals are added**
Running opasDataLinker on 1.6million plus references can take a REALLY long time.  More than a day, maybe two, or three.  (At least on my PC.)  I've only let it run overnight so far.  So I've been working on ways to refine and search less via the command line options.

         Filters
         --key             Process records with the specified PEP article id, regex allowed (e.g., --key AIM.076.0309A)
         --type            Process type 'books' or 'journals' only (abbr. b or j)
         --where           Process by conditional against api_biblioxml table, e.g., ref_year > 2010

You can specify a single journal code to link by using a regex in the key argument like IJP\..* which will only process IJP articles. 
Or you can use IJP.* which will use IJP as the article ID prefix (including IJPOPEN, IJPSP, etc.

If you are adding a new journal, you can specify --type journal and it will only (try to) process references to journals, which would entail only the new journal.  I might also add an option for specifying the journal code which we're trying to match.  Though that sort of thing is easier to do locally than on AWS in the pre setup configs.

To run two scans simultaneously, you can use:

    --halfway --reverse
   and
    --halfway

To start from both ends and quit in the middle of the scan, going "twice as fast", presumably

**Comment by nrshapiro** [comment]
I ran the above on Friday on my PC to link:

opaslinker --unlinked --halfway
opaslinker --unlinked --halfway --reverse

.. and it just finished this morning!  The timing/performance is in the table below.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/4837554/220109243-ae2e2c69-024d-4a05-8805-a16188b0f25a.png">

The reason the total scanned is not half of the total records is the --unlinked flag.  It only scans records that are not already linked with rx or rxcf data.  Here's a sample of the default help.  More options are presented if you use --help.


```
        ********************************************************************************
            opasDataLinker - Open Publications-Archive Server (OPAS) Reference Linker
                            Version 2023.0220/v1.0.010
        ********************************************************************************


        - Read the api_biblioxml table and link articles in PEP.

        Example Invocation:
                $ python opasDataLinker.py

        Important option choices:
         -h, --help        List all help options
         -a                Process all records
         --halfway         Process only half the records, so you can run two
                              instances, one forward, one in reverse

         Filters
         --key             Process biblio records with the key=article-id
                              or regex (e.g., --key AIM.076.0309A, or AIM.*)
         --nightly         Process biblio records added since the day before
         --oldest          Process biblio records least recently updated last
         --type            Process type 'books' or 'journals' only (abbr. b or j)
         --unlinked        Process only unlinked--rx and rxcf--records
         --where           Process by conditional against api_biblioxml
                              table, e.g., ref_year > 2010


         Processing Order
         --reverse         Process biblio records in reverse order by
                              article id, local id
         --oldest          Process oldest (in terms of last updated) biblio
                              records first

        After running opasDataLinker, run opasDataLoader with the

              --smartbuild

        option to reprocess any articles which have new links
        from opasDataLinker. This will build new compiled (output) xml files for those
        with the link data embedded.


Checking only unlinked--rx and rxcf--records.
Scanning biblio table records in ASC order.
Finding candidate references...
Limiting to halfway--418726 of 837451 references.
```

**Comment by nrshapiro** [comment]
@jordanallen-dev - This issue describes what's needed to run opasDataLinker.

**Comment by jordanallen-dev** [comment]
> @jordanallen-dev - This issue describes what's needed to run opasDataLinker.

Correct me if I'm wrong, but running the full data linker took 120 hours?

60hr halfway and 60hr halfway reverse?

So our CI process needs to support a very long timeout duration

**Comment by jordanallen-dev** [comment]
> > @jordanallen-dev - This issue describes what's needed to run opasDataLinker.
> 
> Correct me if I'm wrong, but running the full data linker took 120 hours?
> 
> 60hr halfway and 60hr halfway reverse?
> 
> So our CI process needs to support a very long timeout duration, even if we run both at the same time

**Comment by nrshapiro** [comment]
> > @jordanallen-dev - This issue describes what's needed to run opasDataLinker.
> 
> Correct me if I'm wrong, but running the full data linker took 120 hours?
> 
> 60hr halfway and 60hr halfway reverse?
> 
> So our CI process needs to support a very long timeout duration even if we run both at the same time

Yes.  Or you could run more instances of it at a time using the other options, like --key with a pattern as we discussed when I first noticed how long it was taking.  E.g., you can divide it into smaller chunks using the first letter of the api_key:

A	246241
B	34112
C	63238
D	3254
F	19038
G	6090
I	241545
J	149956
L	17725
M	10289
N	21922
O	9867
P	584521
R	143235
S	30731
T	10146
Z	24161:

Based on the above, I've split by the reference counts, and then for the larger reference counts for A, I, and P, split into halves.  Note that using unlinked will reduce the numbers somewhat or even significantly (the counts above don't take that into effect)

opasdatalinker --key "^A.*" --halfway --unlinked
opasdatalinker --key "^A.*" --halfway --reverse --unlinked
opasdatalinker --key "^[B-D].*" --unlinked
opasdatalinker --key "^[F-G].*" --unlinked
opasdatalinker --key "^I.*" --halfway --unlinked
opasdatalinker --key "^I.*" --halfway --reverse --unlinked
opasdatalinker --key "^J.*" --unlinked
opasdatalinker --key "^[L-O].*" --unlinked
opasdatalinker --key "^P.*" --halfway --unlinked
opasdatalinker --key "^P.*" --halfway --reverse --unlinked
opasdatalinker --key "^R.*" --unlinked
opasdatalinker --key "^[S-Z].*" --unlinked

**Comment by nrshapiro** [comment]
@jordanallen-dev 

Per comments at the meeting, some additional thoughts RE Running all the processes for opasdatalinker per above: I run close to that many at once on my PC.  I would think an AWS machine would be at least as capable.  Anyway, worth a try, or you can discuss that with AWS techs.

**Comment by jordanallen-dev** [comment]
> @jordanallen-dev
> 
> Per comments at the meeting, some additional thoughts RE Running all the processes for opasdatalinker per above: I run close to that many at once on my PC. I would think an AWS machine would be at least as capable. Anyway, worth a try, or you can discuss that with AWS techs.

Depends what specs we have the machine set to. Can always increase it too if necessary so no reason we can't run it as described above

**Comment by jordanallen-dev** [comment]
Run nightly linker with daily scheduled data loads as part of https://gitlab.com/Psychoanalytic-Electronic-Publishing/pep-deployment/-/commit/b9c74d0cf15109cb75b684541b2fce753b69405c

Added ability to run full linker in default and unlinked mode via CI as well

@nrshapiro Is this ready to close now?

**Comment by nrshapiro** [comment]
Nightly looks good.  Haven't tested full, but we can cross that bridge when we need it.

**Comment by jordanallen-dev** [comment]
> Nightly looks good. Haven't tested full, but we can cross that bridge when we need it.

I tested a full one - the one that took about 26 hours to run if you remember?

**Comment by nrshapiro** [comment]
There's nightly.  (automatic)
There's unlinked, invoked manually
there's full, involved manually

I think you ran with the unlinked flag, did you not?

**Comment by jordanallen-dev** [comment]
> @jordanallen-dev
> 
> There's nightly. (automatic) There's unlinked, invoked manually there's full, involved manually
> 
> I think you ran with the unlinked flag, did you not?

Ah yeah, so we haven't tested full. Got it
