### ISSUE TITLE
Duplicate "Ghost" entries created when files are merged/renamed into different IDs. Need an 'opasDataCleaner' in updates.

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#181]
@jordanallen-dev @davidtuckett @ocappello @SophieMBennett 

The current data management process has exposed an issue with server updates via opasDataLoader.  If you are doing an incremental update of the database and content has been merged/renamed into different IDs, or deleted, you can end up with "ghosts":  Documents that are still loaded in Solr, but no longer exist, and in fact, may exist under different IDs.  

This shouldn't happen very often, but it can happen, as recently seen.  We need an easy way to deal with that.  And in fact, I had already developed one for a previous case, but at that time I didn't think it would be needed in the regular processing.

I developed opasDataCleaner for specialized cleaning of Solr and MySQL, on my local machine, for two issues: 
- anomalous entries I saw where a document was loaded into Solr without an art_id
- removal of vestigial documents (moved or deleted), mainly on my machine.

But per the most current online issue, when Aptara moved and changed documents in NLP.079, I realize that (b) is probably more important than I ever realized for AWS given the new management model.  Fortunately, this should run on AWS just fine.  

So I think we should integrate it into the build process.  I'm thinking it could be run before every UPDATE build (full updates and nightly).  Not full builds.  It takes about 2.5 minutes to run on my local PC, so not a lot of time added to the update processing.

It's already been part of the opas suite source (in with opasDataLoader).  Yesterday, I did some code and documentation cleanup.

Run it simply by the command:

`opasDataCleaner --nocheck`

Option --nocheck skips an "are-you-sure" type prompt.  

This will look at the current document set on pep-web-live-data and compare it to the database, eliminating any ghosts.

Per the help screen below, the --rogues option additionally will look for and remove rogue entries (level1 documents without art_ids)  I don't think we need to run this regularly.

The rest of the options should not be needed on a daily run since the defaults are set to what we would normally want, and the rootfolder default should pick up the same setting used by opasDataLoader in localsecrets.

```
        ********************************************************************************
            opasDataCleaner - Open Publications-Archive Server (OPAS) Data Cleaner
                            Version 2023.0417/v1.0.005
        ********************************************************************************

Usage: opasdatacleaner.py [options] - PEP DataCleaner

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -d ROOTFOLDER, --dataroot=ROOTFOLDER
                        Bucket (Required S3) or Root folder path where data is
                        located
  --prefix=ARTID_PREFIX, --artidprefix=ARTID_PREFIX
                        Article ID/Filename prefix to limit processing
  -l LOGLEVEL, --loglevel=LOGLEVEL
                        Level at which events should be logged (DEBUG, INFO,
                        WARNING, ERROR
  --nocheck             Don't prompt whether to proceed.
  --test                Don't commit the delete in solr
  --verbose             Display status and operational timing info as load
                        progresses.
  --outputbuild=OUTPUT_BUILD
                        Specific output build specification,
                        default='(bEXP_ARCH1)'. e.g., (bEXP_ARCH1) or just
                        bEXP_ARCH1.
  --nohelp              Turn off front-matter help
  --rogues              Delete roque records (without art_id) in Solr
  --noclean             Don't clean the DB for missing files (use with rogues
                        to just remove rogues).
```

I'll show a run sample in the next post.

**Comment by jordanallen-dev** [comment]
Added to nightly run as part of https://gitlab.com/Psychoanalytic-Electronic-Publishing/pep-deployment/-/commit/b9c74d0cf15109cb75b684541b2fce753b69405c
