### ISSUE TITLE
Full Update is failing, with no indication why

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#185]
Here's what it says in the build window:

RUN_FULL_UPDATE: Starting incremental load for _PEPFree, _PEPCurrent, _PEPArchive, _PEPSpecial, and _PEPOffsite
5816a6c4207fd45a60d107e511f1175d917ceccccc9ce1cce0848ce9e80b2135
Started data loader container "pep-data-loader-847013076-0" with commands "--sub _PEPCurrent --whatsnewdays 11"
bfc2a595f1462ef5da5ceb6cadc3cb0081e08daa89247c2f7dc9879f9e2e0aff
Started data loader container "pep-data-loader-847013076-1" with commands "--sub _PEPArchive --smartload --halfway"
87dfcd1bc8de19811700a1429ab2a6a87717bee6380344cb167280951d2b92ed
Started data loader container "pep-data-loader-847013076-2" with commands "--sub _PEPArchive --smartload --reverse --halfway"
3daccb01b206c7c4974fbcca9d3a1f5d30948329aceda50b812c8b14fd01a655
Started data loader container "pep-data-loader-847013076-3" with commands "--sub _PEPSpecial --smartload"
8c4d2c648cb556ced122997b3cda35b0981bedf6004b83[173](https://gitlab.com/Psychoanalytic-Electronic-Publishing/pep-data-migration/-/jobs/4169182983#L173)3dcee7f51f3570a
Started data loader container "pep-data-loader-847013076-4" with commands "--sub _PEPOffsite --smartload"
9128d79b2b2c[180](https://gitlab.com/Psychoanalytic-Electronic-Publishing/pep-data-migration/-/jobs/4169182983#L180)9e5104c93a7c371f32cd02fd39b2b268fec5eddcefe4f6ca4
Started data loader container "pep-data-loader-847013076-8" with commands "--sub _PEPFree --smartload"
Waiting for container(s) to complete...
...........There was a problem importing data. Check logs to see which container(s) failed.
TotalContainerCount: 7
ExitedContainerCount: 6
SuccessfulExitedContainerCount: 5

I looked in all the logs and saw no errors.

https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/OpasDataLoader

One log still seems to show the program "running", but like before, there's no additional logging.

It might be good to add the --verbose flag to all of these.

**Comment by jordanallen-dev** [comment]
I think the error is here:

https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/OpasDataLoader/log-events/bfc2a595f1462ef5da5ceb6cadc3cb0081e08daa89247c2f7dc9879f9e2e0aff

They appear out of order most of the time due to how many we having
operating in parallel

**Comment by jordanallen-dev** [comment]
> I think the error is here: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/OpasDataLoader/log-events/bfc2a595f1462ef5da5ceb6cadc3cb0081e08daa89247c2f7dc9879f9e2e0aff They appear out of order most of the time due to how many we have operating in parallel
> […](#)

@nrshapiro Related to the same Locator stuff as before?

**Comment by nrshapiro** [comment]
> > I think the error is here: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/OpasDataLoader/log-events/bfc2a595f1462ef5da5ceb6cadc3cb0081e08daa89247c2f7dc9879f9e2e0aff They appear out of order most of the time due to how many we have operating in parallel
> > […](#)
> 
> @nrshapiro Related to the same Locator stuff as before?

Not sure what you mean, but FWIW, it's just related to the "old" way of using locators, which was an object, and the newer way I started with in the server, where I resolved to just pass around the string article ID.  The locator is an article ID but is actually a class with lots of information already broken down.  The new "integration" of the older XML processing code and the newer system now uses both, because a) there was a lot of code dependent on the locator object that had to be integrated in and b) the locator concept (class) is quite useful.  

Over the weekend I actually caught an instance in nearby code where the locator was passed to an instance expecting a string article id, and fixed that, but I didn't see the two instances here, one of which was hit by the error.  The problem isn't where the error was caught, it was in returning the locator elsewhere which was then passed in.

Fixed it before bed last night and reran...now working.  Thanks for the heads up on where the error was.

I switched --verbose on as a default just in case.  But If you wouldn't mind, I think it would be useful if the calls in full update used the --verbose flag.  Can you please add that?

@jordanallen-dev

**Comment by jordanallen-dev** [comment]
> > > I think the error is here: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/OpasDataLoader/log-events/bfc2a595f1462ef5da5ceb6cadc3cb0081e08daa89247c2f7dc9879f9e2e0aff They appear out of order most of the time due to how many we have operating in parallel
> > > […](#)
> > 
> > 
> > @nrshapiro Related to the same Locator stuff as before?
> 
> Not sure what you mean, but FWIW, it's just related to the "old" way of using locators, which was an object, and the newer way I started with in the server, where I resolved to just pass around the string article ID. The locator is an article ID but is actually a class with lots of information already broken down. The new "integration" of the older XML processing code and the newer system now uses both, because a) there was a lot of code dependent on the locator object that had to be integrated in and b) the locator concept (class) is quite useful.
> 
> Over the weekend I actually caught an instance in nearby code where the locator was passed to an instance expecting a string article id, and fixed that, but I didn't see the two instances here, one of which was hit by the error. The problem isn't where the error was caught, it was in returning the locator elsewhere which was then passed in.
> 
> Fixed it before bed last night and reran...now working. Thanks for the heads up on where the error was.
> 
> I switched --verbose on as a default just in case. But If you wouldn't mind, I think it would be useful if the calls in full update used the --verbose flag. Can you please add that?
> 
> @jordanallen-dev

Great stuff!

Definitely useful. I'll add that now
