### ISSUE TITLE
Similar Docs

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#51]
@nrshapiro Im working on the card for similar docs and having issues.

I see it working on this api call

`https://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&similarcount=2&&facetfields=art_lang%2Cart_year_int%2Cart_views_last12mos%2Cart_cited_all%2Cart_type%2Cart_sourcetype%2Cart_sourcetitleabbr%2Cglossary_group_terms%2Cart_kwds_str&limit=20&offset=0&smarttext=test&synonyms=false`

but when I try to use it for just a single document

`https://stage-api.pep-web.rocks/v2/Documents/Document/ZBK.081.0005A/?similarcount=2`

nothing is returned. Am I misusing the endpoint or should that be working?

**Comment by nrshapiro** [comment]
Yes, that's a bug/omission.  If you look at the interactive Docs page, _**there's no similarcount parameter**_ for /Documents/Document...there's one for /Documents/Abstracts/.  I was thinking you'd get these in abstract mode, but obviously, it would be good for either mode.  I will fix that in the next release.  Meanwhile, you can pick those up in the Abstract call.

**Comment by nrshapiro** [comment]
This has been pushed to staging and production.
