### ISSUE TITLE
Expert Picks

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#52]
@nrshapiro ,

I'm taking a look at the expert picks sidebar widget. I believe we will need either

1. A new endpoint called `/expert-picks`
This endpoint would take the ID's from the admin config and load all the documents and return them

OR

2. The ability to load multiple documents by id - perhaps from the search endpoint
@billdami mentioned that this might already be possible using something like

```
?smarttext={string}   recognizes if you put in a exact document identifier
or you might be able to do like fulltext1?=documentID:(123) OR documentId:(456)
```

Is this currently possible? Thoughts?

**Comment by nrshapiro** [comment]
@bakerac4  

Bill is close.

`art_id:(IJP.076.0315A || AIM.062.0193A || PSC.055.0145A || REVAPA.002.0274A)`
or
`art_id:(IJP.076.0315A or AIM.062.0193A or PSC.055.0145A or REVAPA.002.0274A)`

|| is the same as OR, but might look nicer in your code and saves the server from having to convert or/OR to it.  (Likewise && is AND.)

in the fulltext1 parameter would be best (it works in smarttext too, but if you do include anythin unusual, smarttext will be trying to interpret it.)
