### ISSUE TITLE
glossary_group_terms missing on document load

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#56]
@nrshapiro 

Im working on the glossary terms card/widget. According to the specs, "The gloassary_group_terms facet is returned automatically with the document (or abstract) request"

But when I try to load a document 
https://stage-api.pep-web.rocks/v2/Documents/Document/IJP.027.0099A/?similarcount=5

I don't see anything returned like that. I was hoping you could take a look?

**Comment by nrshapiro** [comment]
I don't think that's true by design..where do you see that?  In the server docs, or the design spec?  Can you be more specific where you see that statement?

**Comment by bakerac4** [comment]
![Screen Shot 2020-09-11 at 9 45 21 AM](https://user-images.githubusercontent.com/9952936/92932932-933c9b00-f413-11ea-94e5-80092758c45c.png)

**Comment by nrshapiro** [comment]
@bakerac4 That's a requirement for what the client does...it doesn't say anything about the server.  The server always requires that you specify any facets you want returned, if any.

**Comment by nrshapiro** [comment]
@bakerac4  (Actually, assuming that's my direct quote, perhaps I meant that I "should do that" for the client side).  But it is currently not done by the server...let me look into it...)

**Comment by nrshapiro** [comment]
@bakerac4 

Looks like I had that in an older version, but for a whole chain of library call "upgrade" reasons, it was no longer being passed through. 

Anyway, realizing there's no way for the client to specify facets in those calls, I added it back in.  Next push, hopefully late today or over the weekend.

**Comment by nrshapiro** [comment]
This is confirmed to be working as of 21 days ago...but reconfirmed in the latest so I can close.
