### ISSUE TITLE
Document with relatedrx

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#58]
@nrshapiro Im having a tough time finding a document with a relatedrx. Would you be able to point one out to me?

**Comment by nrshapiro** [comment]
@bakerac4 

http://www.pep-web.org/document.php?id=APA.033.0473A

![image](https://user-images.githubusercontent.com/4837554/93258713-bb5a3000-f76c-11ea-907f-f49af993a909.png)

clicking the icon

![image](https://user-images.githubusercontent.com/4837554/93258777-d88efe80-f76c-11ea-8980-2bf5b9729da0.png)

More IDs (enter just the id in SmartSearch to go there):
```
APA.040.0256A
APA.034.0047A
APA.035.0539A
APA.033.0725A
APA.034.0489A
APA.034.0488A
APA.036.0105A
APA.036.0393A
APA.036.0429A
```
