### ISSUE TITLE
Reason for Check

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#62]
@nrshapiro 
Hi Neil,
Are your permit requests populating the ReasonForCheck parameter?  I see no evidence that it is.
Thanks
James

**Comment by nrshapiro** [comment]
I hadn't done it yet, but it was the perfect opportunity this morning, since I had no other pending changes...so I just did it.  I just ran a test run and I will upload it to stage shortly.

**Comment by jwoosnam** [comment]
@nrshapiro  Please let me know when I should be seeing the results coming though to PaDS and I will check.

**Comment by nrshapiro** [comment]
@jwoosnam this is in place.  

I am retooling the server to use ONLY pads authentication now (even for testing), so you should be seeing lots of requests coming in, at least from my test routines as I check the changes.
