### ISSUE TITLE
Uvicorn logging

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#66]
Uvicorn logs all the endpoint calls when its logging is set to info.  This is why we have all the heartbeats logged in the Cloudwatch logs.  While these have been lessened, they still interfere.

I have a solution for that...hopefully...here:

1) @leyla - in your launch script for the server, can you please set the loglevel for uvicorn to WARNING.  
2) OPAS  _2020.1012.2.Alpha_ now logs the endpoints (and the parameters) for all endpoints we care about (excluding the Api/Status endpoint~)
3) OPAS should still come up in INFO logging mode, for now.  Eventually, we'll want it to default to WARNING.
3) Opas _2020.1012.2.Alpha_ now has an endpoint which will let me dynamically change it's loglevel.  What I don't know yet, is whether that will change Uvicorns logging--I don't want it to, and it works fine here, where I've confirmed it changes OPAS but not Uvicorn.

**Comment by nrshapiro** [comment]
@leyla - this doesn't seem to have affected uvicorn.  Still logging info events.  (Also, firewall still letting bots through.)

**Comment by lhorne-gavant** [comment]
@nrshapiro 
I believe setting uvicorn logging to "warning" worked as documented but to stop logging endpoint access what we actually want to do is disable access logs. I've submitted a PR #70 to do this. 

Here's an example of uvicorn set to "warning"
![Screen Shot 2020-10-20 at 9 31 58 AM](https://user-images.githubusercontent.com/49171096/96595517-bfbcc000-12b9-11eb-9c83-27944752b29e.png)

versus uvicorn set to "info"
![Screen Shot 2020-10-20 at 9 32 21 AM](https://user-images.githubusercontent.com/49171096/96595549-c814fb00-12b9-11eb-97ae-f05298c5b88d.png)

Both were still logging endpoint access.

I'll take another look at adding more firewall rules.

**Comment by nrshapiro** [comment]
@lhorne-gavant 

That appears to have done the trick!
