### ISSUE TITLE
Reporting Queries

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#73]
@nrshapiro 
I few reporting queries:

- How can I tell the language of a document?
- Do you store co-authors separately?  If so, how do I get to it?  I need to report on them independently.

Thanks

**Comment by nrshapiro** [comment]
@jwoosnam 
You can get all document metadata using the API, including language and authors.  You can use /v2/Documents/Abstract (or you can even use search by putting the article ID in the smartSearch parameter.

**Comment by nrshapiro** [comment]
@jwoosnam 
While it would be less "protected" against changes in infrastructure, you could also connect to the AWS-RDS database "opascentral" directly, and get article data from table api_articles.

**Comment by jwoosnam** [comment]
@nrshapiro 
My oversight, I can see that the language against the journal, which is fine.
In terms of authors I was hoping you had an authors table with an intersecting "document author" table.  Since this morning I have had a brief discussion with David about this and he says authors have always been troublesome. If the format of the authors field is consistent then I can work with that.
Thanks
