### ISSUE TITLE
IJP Open Discussion IJOD

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#74]
@nrshapiro 
I am concerned about how this works, particularly for Permits.  Is it just like any other Journal?  Is there metadata I can import?

**Comment by nrshapiro** [comment]
IJPOpen is not currently planned to be a part of PEP-Web 2021.  

But if it were:
- currently there is an XML document for each IJPOpen document.  It's all metadata (abstract etc., and some addl data, in a special front matter field addldata.
- within the document, there's a link to a PDF, which is the article itself.  The XML only contains the metadata and abstract.
- IJPOpen articles are not "constant".  They can and will be be removed by IJP at some point.  This is perhaps the biggest problem besides the completely different presentation format they use, IMO.

![image](https://user-images.githubusercontent.com/4837554/99078885-2073ab80-258d-11eb-8f2c-f4b321be3e23.png)
