### ISSUE TITLE
Paths in config/localsecrets

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#79]
Leyla - The image path in localsecrets is pointing to S3, right?

The graphic file retrieved bannerPEPGrantVSLogo.gif was being referenced by the client as bannerPEPGRANTVSLogo.gif, so I changed the S3 name to bannerPEPGRANTVSLogo.gif.

Yet, the client, and even the server doesn't find it via: 
   https://stage-api.pep-web.rocks/v2/Documents/Image/bannerPEPGRANTVSLogo.gif

    {"detail":"Error: bannerPEPGRANTVSLogo.gif not found or no filename specified"}

But 
  https://stage-api.pep-web.rocks/v2/Documents/Image/bannerPEPGrantVSLogo.gif

doesn't produce the error (though the image isn't displayed either for whatever reason.

If I run my local copy using the remote S3 settings, though, the new name works fine.

    def test_0_Image2(self):
        full_URL = base_plus_endpoint_encoded(f'/v2/Documents/Image/bannerPEPGRANTVSLogo.gif/')
        # local, this works...but fails in the response.py code trying to convert self.status to int.
        response = requests.get(full_URL, headers=headers)
        # Confirm that the request-response cycle completed successfully.
        assert(response.ok == True)

What it must come down to is the localsettings on the server?  Where are you pointing the image source path?

Using S3 from here, this path works from s3 for that file:
    IMAGE_SOURCE_PATH = "pep-web-files/doc/g"

Maybe it needs time to propagate?  Or do I need to refresh/restart the server?  In fact, I just did that, and it worked.  The question is: why?

**Comment by nrshapiro** [comment]
@lhorne-gavant 
Leyla...see the questions above.  Still doesn't find that logo file.

**Comment by lhorne-gavant** [comment]
@nrshapiro 

I've confirmed that IMAGE_SOURCE_PATH matches what you expect.

There don't appear to be any files by your new name (bannerPEPGRANTVSLogo.gif) at that s3 path. The file is still called bannerPEPGrantVSLogo.gif

You mentioned that the old url (https://stage-api.pep-web.rocks/v2/Documents/Image/bannerPEPGrantVSLogo.gif/)doesn't produce an error, but also doesn't display the image. It seems to load the image fine for me in browser currently so i'm not sure what might be wrong there. Let me know if this is still an issue for you.

Could you point me to the url/steps to reproduce this error starting from the webapp?

**Comment by nrshapiro** [comment]
@lhorne-gavant 

I changed that name manually--I deleted the old file, then uploaded a new one with the new case.  Now it's back to the old way?

I don't understand how.  I'm going to try again.  I just did that with another file as well...this time, I did it on my local file system ONLY and Goodsync copied over to S3:

133520 Change Name Case: Move File s3s://s3.amazonaws.com/pep-web-files/doc/g/bannerNYPSIvsLogo.gif -> s3s://s3.amazonaws.com/pep-web-files/doc/g/bannerNYPSIVSLogo.gif

And I confirm:

![image](https://user-images.githubusercontent.com/4837554/103816832-99462f80-5033-11eb-93da-1703a4a4442b.png)

But it still doesn't work in the Stage app or server, as the other file did before:

https://stage-api.pep-web.rocks/v2/Documents/Image/bannerNYPSIVSLogo.gif/

fails.

And I suppose this one somehow will revert?!?!?!?!?  Or does it not show up for you like the above?

**Comment by lhorne-gavant** [comment]
@nrshapiro It looks like the file name changes you made to both files are present this time and I can see the failures in browser. It looks to me like the API or a library it's using might be caching s3 paths for some reason.

For example, the renamed files are not being returned by the api but the originally named "bannerPEPGrantVSLogo.gif" that was returning before, is now returning with a broken image:
![Screen Shot 2021-01-06 at 3 41 00 PM](https://user-images.githubusercontent.com/49171096/103817977-a95f0e80-5035-11eb-97b6-9b5ae5f90908.png)

Let me know if you would like me to look into this further.
