### ISSUE TITLE
Reprocessing Build to Remove Stop Words

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#80]
@lhorne-gavant 

I removed the stop words from the stopwords.txt file and instituted a build pipeline command with the --resetcore command (which I realize is probably not necessary for a full build).

It went through the build, and I pushed it to stage.  But the stop words are still being removed.  Since I also did it locally successfully on my PC, I know the build configuration (change to the stopwords.txt file) works.  

Why it doesn't seem to work on the AWS build?

On a side note: It looks like you've set things up for automatic detection and run as well (thanks).  Is that documented?  How does that change procedures when I want a full rebuild but the data files aren't changing (just a configuration file like stopwords.txt)--like this?

**Comment by lhorne-gavant** [comment]
@nrshapiro 
It looks like we only have configuration (schema, stopwords, etc) updating during full rebuilds. Would you prefer that these files be updated on every data load instead?
 
RE:Sidenote - Yes! Every night at 6pm it will run just an incremental load (no command line args). I will add some notes in the readme but the short of it is that you can just find the most recently scheduled pipeline and snapshot/deploy like normal.

**Comment by nrshapiro** [comment]
@lhorne-gavant 

No, schema, stopwords, etc, only should be updated in full rebuilds, since they apply to the full index. 

RE: so where does the incremental build automatically go?  To the Development Solr only, or also to Stage?

**Comment by lhorne-gavant** [comment]
@nrshapiro Ah alright. Next time you set rebuild=true, you should see your stopwords/schema/etc update then. It sounds like no deployment changes need to be made currently.

RE: this is actually just an incremental data load to the development solr server. If you want that new data deployed to staging or production you'll want to click the snapshot and deploy buttons.
