### ISSUE TITLE
DevOps Build Process Optimizations

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#84]
Today may have been a bit unusual, with an error from solr seeming to repeatedly happen, while meanwhile the Development solr database appears to be updated, as does the Development RDS database.  Maybe I'm missing something.

But it's not acceptable that a full build is still running, 20 hours later.  I ran the entire process here in about 4 hours on my PC.  The worst part of this is that if I were really building a production set with a deadline, this would really extend the time...especially if I had to run it more than once.  Even incremental builds don't solve the problem...I don't have timing data, but as I recall the last time I manually ran one, the incremental process takes many hours as well...when in fact, it may only be a handful of files being loaded.  

We need to do better.

Some ideas for improving build performance:

1) In a rebuild scenario, once we see the crossing point of the forward and reverse runs, we should stop or at least let then ext step (build images) proceed...that takes far too long on AWS to finish even though the work is actually done.  And the fact that the process can't "complete" until each direction has looked at all the files, makes me wait hours more.  

So I've added a flag: --halfway which can be used for both the forward and reverse processes--and they will quit after each processing half of the files.  Hopefully, that will help.

2) We could add more processes to the full build...my 4 hour timing is running forward, reverse, and targeting some of the bigger journals separately (only works when resetting the cores, so it's not set to "all" but rather checks if each file is in the database, so overlap with two main processes isn't a problem, and they just zip past when they are already processed (of course it doesn't seem to zip on AWS).  I sometimes run as many as 6 or so processes here on my Intel I9 9900K 8-core PC to optimize the timing.

3) For smaller changes it may be a good idea to make another processing option...where I can make more targeted changes to development solr and development RDS quickly...and then generate what's needed for stage.  I can run my builds remotely on those, and for smaller updates, I think it may run more quickly than the current update process.  Then we'd have a script to create what's needed to create the AMI's to push to stage and eventually production (after testing).  This could even run off of stage, as an option...so after checking stage, if there are some issues, it can be dealt with there, then the AMIs generated and pushed to production.

Though we can discuss why incremental also seems to takes so long before going down that road.  One thing that's odd--I noticed when running incremental builds, it's falsely detecting changes and processing some items, where it shouldn't have to.  Not sure why that happens--it doesn't happen when run locally.  Perhaps something about comparing times between S3 and Solr?

I do have another ace up my sleeve to make it faster...but I'm hesitant because it involves a loss of an interesting search feature (even though the client isn't using it) and requires changes to the server as well.  Still I'm considering it if we can't speed things up.  I'm open to ideas.  I am ok with a 12 hour total for a full build--one I can start in the evening and have it ready in the morning.  I'd prefer faster but I can live with that.  Incremental builds should take very little time, anywhere from 15 minutes at most for a few new files to an hour or two, for example, to rerun the whole PEPCurrent folder (<7000 files).

But I don't think a full build that takes over 20 hours, like the current one is taking, works for starters.  Maybe that's an anomaly, but it's certainly holding me up today...and I don't want to stop it to try again, because it seems to take 14 or more hours to rebuild in any case.

**Comment by nrshapiro** [comment]
I started a build with the --halfway mark last night.  This one also included the new article_tracker data table in RDS which records what article IDs have been seen, so the notify file can be generated at the end of the build (notifying of any new issues/articles).

Each process seems to have run 22K records, and then failed, meaning the database and solr was updated with 44K of the 136K records.  The error is strange...suddenly, after storing 44K records total, running about 6 hours, the ocd database no longer existed in Python's memory, so the commit failed:

```
  | 2021-02-03T07:13:30.596-05:00 | Processing started at (Wed Feb 3 05:32:06 2021).
-- | -- | --
  | 2021-02-03T07:13:30.596-05:00 | --------------------------------------------------------------------------------
  | 2021-02-03T07:13:30.596-05:00 | halfway option selected. Processing approximately one-half of the files that match.
  | 2021-02-03T07:13:30.596-05:00 | Load process started (Wed Feb 3 05:32:06 2021). Examining files.
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.596-05:00 | Committing info for 1000 documents/articles
  | 2021-02-03T07:13:30.597-05:00 | Traceback (most recent call last):
  | 2021-02-03T07:13:30.597-05:00 | File "opasDataLoader.py", line 626, in <module>
  | 2021-02-03T07:13:30.597-05:00 | main()
  | 2021-02-03T07:13:30.597-05:00 | File "opasDataLoader.py", line 484, in main
  | 2021-02-03T07:13:30.597-05:00 | ocd.db.commit()
  | 2021-02-03T07:13:30.597-05:00 | AttributeError: 'NoneType' object has no attribute 'commit'

```
I ran the same forward/backward two process run on my local machine here for PEPArchive (I run PEPCurrent and the other separately).  Here is the log of one of the two processes.  It took 5 hours, and better than that, successfully completed.

```
TCC LE  14.00.9 x64   Windows 10 [Version 6.3.19041]
Copyright 2016 JP Software Inc.  All Rights Reserved

alias /r c:\win32app\4NT4\aliases.txt

    opasDataLoader - Open Publications-Archive Server (OPAS) - Document, Authors, and References Core Loader

        Load articles into the Docs, Authors, and Glossary Solr cores and
        load article information and bibliography entries into a MySQL database
        (RDS or MySQL) as configured in localsecrets). This data loader is specific to the
        PEP Data and Bibliography schemas but can serve as a model or framework for other schemas.

        See documentation at:
          https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/wiki/Loading-Data-into-OpenPubArchive

        Example Invocation:
                $ python opasDataLoader.py

        Important option choices:
         -h, --help  List all help options
         -a          Force update of files (otherwise, only updated when the data is newer)
         --sub       Start with this subfolder of the root (can add sublevels to that)
         --key:      Do just one file with the specified PEP locator (e.g., --key AIM.076.0309A)
         --nocheck   Don't prompt whether to proceed after showing setting/option choices

        Example:
          Update all files from the root (default, pep-web-xml) down.  Starting two runs, one running the file list forward, the other backward.
          As long as you don't specify -a, they will skip the ones the other did when they eventually
          cross

             python opasDataLoader.py
             python opasDataLoader.py --reverse

          Update all of PEPCurrent

             python opasDataLoader.py -a --sub _PEPCurrent

        Note:
          S3 is set up with root pep-web-xml (default).  The root must be the bucket name.

          S3 has subfolders _PEPArchive, _PEPCurrent, _PEPFree, _PEPOffsite
            to allow easy processing of one archive type at a time simply using
            the --sub option (or four concurrently for faster processing).


Messaging verbose:  False
Input data Root:  X:\_PEPA1\_PEPa1v
Input data Subfolder:  _PEParchive
Reset Core Data:  False
Forced Rebuild - All files added, regardless of whether they are the same as in Solr.
********************************************************************************
Database will be updated. Location: localhost
Solr Full-Text Core will be updated:  http://localhost:8983/solr/pepwebdocs
Solr Authors Core will be updated:  http://localhost:8983/solr/pepwebauthors
Solr Glossary Core will be updated:  http://localhost:8983/solr/pepwebglossary
********************************************************************************
Locating files for processing at X:\_PEPA1\_PEPa1v\_PEParchive with pattern \((bEXP_ARCH1|bSeriesTOC)\)\.(xml|XML)$. Started at (Tue Feb  2 19:27:58 2021).
--------------------------------------------------------------------------------
Ready to import records from 129966 files at path X:\_PEPA1\_PEPa1v\_PEParchive
Processing started at (Tue Feb  2 19:28:23 2021).
--------------------------------------------------------------------------------
halfway option selected.  Processing approximately one-half of the files that match.
-r option selected.  Running the files found in reverse order.
Load process started (Tue Feb  2 19:28:23 2021).  Examining files.
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Committing info for 1000 documents/articles
Halfway mark reached on file list (64984)...file processing stopped per halfway option
Load process complete (Wed Feb  3 00:29:09 2021).
Performing final commit.
Issue updates.  Writing file ./dataUpdateLogs/updated_issues_20210203-002911.xml
Finished! Imported 64985 documents and 15 references. Total file inspection/load time: 18048.07 secs (300.80 minutes.)
...Files loaded per Min: 216.0397
...Files evaluated per Min (includes skipped files): 432.0661
Note: File load time is not total elapsed time. Total elapsed time is: 18048.07 secs (300.80 minutes.)
Files per elapsed min: 216.0397
```

**Comment by lhorne-gavant** [comment]
@nrshapiro I'm looking into the mysql error you were seeing to try to get you back up and running first and foremost and I believe the issue is that having the loaders run for so long exhausted the RDS instance I/O burst balance. This balance is dependent on volume size and takes time to reaccumulate when used. To start, I've increased the development RDS volume size (you were running low on disk space anyway). Once the burst balance regenerates a bit you should have better database performance.

**Comment by nrshapiro** [comment]
@lhorne-gavant @adistasio 

1) The processes that you restarted a few hours ago are still running ok...that's good.  Did you use the new --halfway option to keep them from needing to go through all the overlapping files?

2) Another thing I've been noticing, not sure if this has changed for some reason.  You can't see any logs for the processes until there's some sort of error.  For example, the processes you've started aren't listed in the log groups...the last ones listed are from this morning where there was an error.  Is this a change from previous behavior?  What determines when the output appears in the cloudwatch list?  Does it have to cross some length threshold?

**Comment by lhorne-gavant** [comment]
@nrshapiro 
1. I did see the new option and my last run is with "-a --halfway".
2. That is interesting. I have not made any changes to logging. I do believe it is buffered up to a certain amount for efficiency before sending, but having no logs at all until there is an error is no good. I'll see if i can't get us logging more frequently for future runs.

**Comment by lhorne-gavant** [comment]
@nrshapiro I just wanted to give you an update on where the data migration changes are at this morning.
1. I've decreased logging and made it more user friendly since you occasionally check them out. 
2. Updated to fail fast if any container fails
3. Updated to run doc folders separately instead of running from the parent directory. Last nights incremental load took 4 hours.
4. Updated such that the --resetcore flag will now cause _PEPFree to be run with resetcore, followed by normal processing based on any other flags you've sent in, minus resetcore. You should be able to use the "commands" var like usual. Let me know of you see any oddities. I'm still testing these changes, but you should be able to trigger pipelines if you'd like.

I took a look at the cloudwatch log sending delays, but haven't come up with a solution yet. That's on the agenda for today as well as working on the email issues.

**Comment by nrshapiro** [comment]
Thanks Leyla.  The execution time seems good, but I just tried looking 
at all the jobs logs from your runs...see one that runs for PEPFree, but 
I don't see any other folders run...and all are overrun by the stat 
update logging display (which I can certainly limit).  I had to look at 
the files in Raw mode to see it because of that--which in itself is not 
a problem.

But can you point me to the right log to see the full build info (not 
just the stat)?

Thanks,

Neil



------ Original Message ------

**Comment by lhorne-gavant** [comment]
@nrshapiro I ran pipelines a few times for testing yesterday. If you look at pipeline 6050 you should see all folders run. You will have to look at it in raw mode because the log is greater than gitlabs capacity. I did notice the stat updaters logging yesterday. Have you by chance changed how you're logging recently? 

```
-------------------- Loading data --------------------
Starting default loaders
0b54f67936660be6d707a2aa7339291bdb30105d4d4e935736c7947219a612c3
Started container "pep-data-loader-6050-0" with commands "  --sub _PEPFree"
4120f78587e5f3c7a13b795c914f6bd966fab04d1d8c6fc7a04b9e51be90ce74
Started container "pep-data-loader-6050-1" with commands "  --sub _PEPOffsite"
089b0eb97bc1d61bf027539fbfed1c19b39da32089b65f9b9139494039cfc8ad
Started container "pep-data-loader-6050-2" with commands "  --sub _PEPCurrent"
602f4c3dc4cbad092ebb526097acb93fe8289bb0e4a622b1de4873bb5fd046ca
Started container "pep-data-loader-6050-3" with commands "  --sub _PEPArchive --halfway"
66fd7b679c29d13b8dbc87127c24a419eac216bf6b104d52a9c5749ba76427cb
Started container "pep-data-loader-6050-4" with commands "  --sub _PEPArchive --reverse --halfway"
```

**Comment by nrshapiro** [comment]
Yes, I changed the way it worked so only records with data are getting 
updated.  But that message (error trap for a missing document or stat 
field) never gets hit when I run it here.  It should look like the 
example below...but I'm going to try running it remotely and see what 
happens with the data that's online.

opasDataUpdateStat version 2021.0204.1 started at 2021-02-05 10:38:26.
2021-02-05 10:38:26 opasDataUpdateStat open_connection 126 - DEBUG 
Database opened by (get_most_viewed_crosstab) Specs: opascentral for 
host localhost,  user root port 3306
2021-02-05 10:38:26 opasDataUpdateStat close_connection 143 - DEBUG 
Database closed by (get_most_downloaded_crosstab)
Collecting citation counts from cross-tab in biblio database...this will 
take a minute or two...
2021-02-05 10:38:26 opasDataUpdateStat open_connection 126 - DEBUG 
Database opened by (collect_citation_counts) Specs: opascentral for host 
localhost,  user root port 3306
2021-02-05 10:38:38 opasDataUpdateStat close_connection 143 - DEBUG 
Database closed by (collect_citation_counts)
Merging up to 44813 stat records into Solr Docs core records.
...44000 records to go
...43000 records to go
...42000 records to go
...41000 records to go
...40000 records to go
...39000 records to go
...38000 records to go
...37000 records to go
...36000 records to go
...35000 records to go
...34000 records to go
...33000 records to go
...32000 records to go
...31000 records to go
...30000 records to go
...29000 records to go
...28000 records to go
...27000 records to go
...26000 records to go
...25000 records to go
...24000 records to go
...23000 records to go
...22000 records to go
...21000 records to go
...20000 records to go
...19000 records to go
...18000 records to go
...17000 records to go
...16000 records to go
...15000 records to go
...14000 records to go
...13000 records to go
...12000 records to go
...11000 records to go
...10000 records to go
...9000 records to go
...8000 records to go
...7000 records to go
...6000 records to go
...5000 records to go
...4000 records to go
...3000 records to go
...2000 records to go
...1000 records to go
...0 records to go
Finished updating Solr stat with 23 article records updated; records 
skipped: 0.
Fri Feb  5 10:44:57 2021 Updated 23 Solr records in 391.5411148071289 
secs (6.525685246785482 minutes)).

------ Original Message ------

**Comment by nrshapiro** [comment]
From the last run, it looks right.

-------------------- Loading data --------------------
Starting default loaders
5058ee401dd1be5cec26df520ec29181b8c1e683b6d4880083f6022225fe29db
Started container "pep-data-loader-6064-0" with commands "  --sub _PEPFree"
09286bc982a5f4775d6a32528f75f3b9c247225a2bb88130e276273b1806dd01
Started container "pep-data-loader-6064-1" with commands "  --sub _PEPOffsite"
e58583f0288b12b8b5f24dd70977dd7fcada339536bf45dd5edcb6f627a2700c
Started container "pep-data-loader-6064-2" with commands "  --sub _PEPCurrent"
795fe95e8c7977205c04902732dd092ed49c5795321253a5541c9e81073a12be
Started container "pep-data-loader-6064-3" with commands "  --sub _PEPArchive --halfway"
e34dd1c2746bbfe990908ae1f84118da455bc1b3601b65d308d67d2e272f33f4
Started container "pep-data-loader-6064-4" with commands "  --sub _PEPArchive --reverse --halfway"
Waiting for container(s) to complete...
...................................................
Successfully loaded data
-------------------- Restarting Solr --------------------
Stopping old docker container
pep-solr
pep-solr
Removing old docker container
pep-solr
Starting new container
ae1d94e85c841e2587a47fdc35e622ef935441c45d50f88cc3a03ad4e19f5a64
-------------------- Running Stat Updater --------------------
    opasDataUpdateStat - Program to update the view and citation stat fields in the pepwebdocs
      database.
      
      By default, it only updates records which have views data.
      If you use command line option --all, it will add all citation and views data to the
        pepwebdocs data.  (This takes significantly longer.)
        
         - The first update after a load should be with option --all
         - Then, omit --all to update views daily
         - Citations (include --all) only need be updated after data updates
         
         For complete details, see:
          https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/wiki/Loading-Data-into-OpenPubArchive
      The records added are controlled by the database views:
         vw_stat_docviews_crosstab
         vw_stat_cited_crosstab
         
      2020-10-29 Important update - Since it is used at database build/rebuild time, it now updates all records
         where views are non-zero, not just the last week.
    
opasDataUpdateStat version 2021.0205.1 started at 2021-02-05 20:24:30.
Collecting citation counts from cross-tab in biblio database...this will take a minute or two...
Merging up to 45211 stat records into Solr Docs core records.
...45000 records to go
...44000 records to go
...43000 records to go
...42000 records to go
...41000 records to go
...40000 records to go
...39000 records to go
...38000 records to go
...37000 records to go
...36000 records to go
...35000 records to go
...34000 records to go
...33000 records to go
...32000 records to go
...31000 records to go
...30000 records to go
...29000 records to go
...28000 records to go
...27000 records to go
...26000 records to go
...25000 records to go
...24000 records to go
...23000 records to go
...22000 records to go
...21000 records to go
...20000 records to go
...19000 records to go
...18000 records to go
...17000 records to go
...16000 records to go
...15000 records to go
...14000 records to go
...13000 records to go
...12000 records to go
...11000 records to go
...10000 records to go
...9000 records to go
...8000 records to go
...7000 records to go
...6000 records to go
...5000 records to go
...4000 records to go
...3000 records to go
...2000 records to go
...1000 records to go
...0 records to go
Finished updating Solr stat with 128 article records updated; records skipped: 0.
Fri Feb  5 20:29:15 2021 Updated 128 Solr records in 284.55176043510437 secs (4.742529340585073 minutes)).
-------------------- End Load solr data --------------------
Running after_script
00:02
Running after script...
$ bash utilities.sh CleanupDockerBuild "$SvcName-loader-$CI_PIPELINE_ID"
-------------------- Docker cleanup --------------------
Stopping container(s)
"docker stop" requires at least 1 argument.
See 'docker stop --help'.
Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]
Stop one or more running containers
"docker rm" requires at least 1 argument.
See 'docker rm --help'.
Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]
Remove one or more containers
Removing image(s)
Untagged: pep-data-loader-6064:latest
Deleted: sha256:7427e4b9e2d2f99b405113a44b2aebd832ce5278cb0622602eaf0bf166fcf584
Deleted: sha256:d942427b21d56966208b7e1cec999f801fab09a3f987017da16115ab13527704
Deleted: sha256:d603ebda2b6b744f730e54c427d79061361b5cfc9f20bad787a9e45e55952d38
Deleted: sha256:76144d5f30b0e35102bdf0aaee64e6153d2153348bb6fad73a983293a059019c
Deleted: sha256:35b855c4336e960bb780844048a94a4d30857dfd01c8903d694d8a3ab0a33996
Deleted: sha256:78f3fcb7a84cb867b2e08164b4f35f142e8d6f9417f71fd9e996b267619d07df
Deleted: sha256:5e0e26c66c2912746cbfd2e89ec91a3192675312451055db13dc631c621d04f5
Deleted: sha256:93be0129ac3f22fb5f36b60e618d64a3ac60ea925ae88cc92b7d01b141d6456a
Deleted: sha256:e037e0d134993ad60275a57c12b4042ba608d5998b523199544f61991f65fffa
Deleted: sha256:118f61bef2489be224549b2dc46904a12e009d34137f6efa8d4458d48e9b4be4
Deleted: sha256:6012991a972a959b24030aa1fee8e3e6b615e78bca1ed8c5f47df24412c37ec2
After cleanup
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
pep-data-loader-6030                latest              31730ab774c6        42 hours ago        1.26GB
pep-data-loader-5967                latest              e67a95156d0a        3 days ago          1.26GB
tiangolo/uvicorn-gunicorn-fastapi   python3.7           57c75d7c41d8        8 months ago        970MB
-------------------- End Docker cleanup --------------------
Job succeeded

**Comment by nrshapiro** [comment]
Not much in the above record about the actual (incremental) data load, so I looked in Cloudwatch for the results, and that looks good.  It only found two new data items, and thankfully, the total time to walk through 130K records to check was just under 40 minutes.  Excerpted here:

```

  | 2021-02-05T19:01:22.242-05:00 | Skipped 128800 so far...loaded 2 out of 129965 possible.
-- | -- | --
  | 2021-02-05T19:01:22.242-05:00 | Skipped 128900 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129000 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129100 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129200 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129300 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129400 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129500 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129600 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129700 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129800 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Skipped 129900 so far...loaded 2 out of 129965 possible.
  | 2021-02-05T19:01:22.242-05:00 | Load process complete (Sat Feb 6 00:01:22 2021).
  | 2021-02-05T19:01:22.242-05:00 | Performing final commit.
  | 2021-02-05T19:01:22.242-05:00 | Finished! Imported 2 documents and 36 references. Total file inspection/load time: 2378.58 secs (39.64 minutes.)
  | 2021-02-05T19:01:22.242-05:00 | ...Files loaded per Min: 0.0505
  | 2021-02-05T19:01:22.242-05:00 | ...Files evaluated per Min (includes skipped files): 3278.3778
  | 2021-02-05T19:01:22.242-05:00 | Note: File load time is not total elapsed time. Total elapsed time is: 2378.58 secs (39.64 minutes.)
  | 2021-02-05T19:01:22.242-05:00 | Files per elapsed min: 0.0505


```
