### ISSUE TITLE
Data Process...Simple...per our current, PEP-Web (GVPi) technique

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#92]
While the current mostly automatic data process is certainly a step ahead of what the process was before, there's still an issue.

As far as I can tell, it runs every night, whether there's new data or not.  I don't know what the expense is of that, but it brings me back to where we originally started.  I want the data process to run in a like manner to what we've been using in PEP-Web (GVPi).  It's simple, only runs when it needs to, and while we have some additional parameters to control, it's easily implemented.

I put together a Python program to show this.  However, I presume this would be better implemented in shell scripts, and of course, I didn't put the actual actions in the program.  It was merely to show the logic.  

But this is what I want for the data process (though there are more control states than I asked for in the beginning).

The stat updater can continue to run updates automatically.  I presume that only goes to Stage...but FILE_GO_LIVE will now push it to production (correct me if I'm wrong about where it goes)

Here's the plan:

1) Periodically start a script, say once every 5 or even 15 minute (please make it configurable, in LOCALSECRETS might be a good place).

2) The script will look for one of these control files in a predetermined location on S3, for example, in the Python program below, they are put in localsecrets.XML_ORIGINALS_PATH.  That should make it quick to find.  

   - "run-current-update.txt" (check current and free folder subtree for new or updated data, process all the way to stage)
   - "run-full-update.txt" (check current and archive folders for new data, run update but keep the database/solr data intact, process all the way to stage)
   - "run-full-rebuild.txt" (Run Full Build, all subtrees, fresh database and schema)
   - "run-send-to-production.txt"  (Push Stage to Production)

3)
   a) If it sees one, it will rename it to base filename + "-running.txt", e.g., "run-full-update-running.txt" and start that data process.
   b) if not, it will exit and do nothing.

4) In the case of 3a, when it finishes, it will delete the txt control file

Simple as that.  Here's the simple logic framework in Python which also has descriptions of the file actions:

```programNameShort = "opasBuildControl"
print(
    f""" 
    {programNameShort} - Open Publications-Archive Server (OPAS) - Remote Execution Protocol
    
        Manage the complete run process by loading txt files to the XML folder.
        
        Watch the XML folder for one of the text files.
        Rename it to suffix it with -running.txt
        When it finishes running, delete the .txt file

    """)
    
import localsecrets
import opasFileSupport
import time
CONTROL_FILE_PATH = localsecrets.XML_ORIGINALS_PATH

FILE_RUN_FULL_UPDATE = "run-full-update.txt"
FILE_RUN_CURRENT_UPDATE = "run-current-update.txt"
FILE_RUN_FULL_REBUILD = "run-full-rebuild.txt"
FILE_GO_LIVE = "run-send-to-production.txt"
FILE_STOP = "run-stop-monitoring.txt"
INTERVAL = 9
ACTION = 2

flex_fs = opasFileSupport.FlexFileSystem(key=localsecrets.S3_KEY,
                         secret=localsecrets.S3_SECRET,
                         root=CONTROL_FILE_PATH) 

def file_exists(document_id, path=CONTROL_FILE_PATH):
    ret_val = flex_fs.exists(filespec=document_id, path=path)
    return ret_val

if file_exists(FILE_RUN_CURRENT_UPDATE, path=CONTROL_FILE_PATH):
    # check current and free folder subtree for new or updated data, process all the way to stage
    print ("Run Update (current) and free subtrees")
    flex_fs.rename(FILE_RUN_CURRENT_UPDATE, FILE_RUN_CURRENT_UPDATE+"-running.txt")
    
    time.sleep(ACTION)  # Placeholder for action call
    
    flex_fs.delete(FILE_RUN_CURRENT_UPDATE+"-running.txt")
    
   
elif file_exists(FILE_RUN_FULL_UPDATE, path=CONTROL_FILE_PATH):
    # check current and archive folders for new data, run update but keep the database/solr data intact, process all the way to stage
    print ("Run Update, archive, free and current subtrees")
    flex_fs.rename(FILE_RUN_FULL_UPDATE, FILE_RUN_FULL_UPDATE+"-running.txt")
    
    time.sleep(ACTION)  # Placeholder for action call
    
    flex_fs.delete(FILE_RUN_FULL_UPDATE+"-running.txt")
    
elif file_exists(FILE_RUN_FULL_REBUILD, path=CONTROL_FILE_PATH):
    
    print ("Run Full Build, all subtrees, fresh database and schema")
    flex_fs.rename(FILE_RUN_FULL_REBUILD, FILE_RUN_FULL_REBUILD+"-running.txt")
    
    time.sleep(ACTION)  # Placeholder for action call
    
    flex_fs.delete(FILE_RUN_FULL_REBUILD+"-running.txt")

elif file_exists(FILE_GO_LIVE, path=CONTROL_FILE_PATH):
    print ("Push Stage to Production")
    flex_fs.rename(FILE_GO_LIVE, FILE_GO_LIVE+"-running.txt")
    
    time.sleep(ACTION)  # Placeholder for action call
    
    flex_fs.delete(FILE_GO_LIVE+"-running.txt")
```

If I left off any needed control states, let me know, but I think that covers what we'd do.  Of course, it should still send email progress and problem reports.

**Comment by lhorne-gavant** [comment]
@nrshapiro 
This feature should be ready to use now. Just add your files to the XML_ORIGINALS_PATH bucket and it will get picked up. I've only done dry runs in certain cases (production deployment) so i will keep an eye on things, but let me know if something seems off.

**Comment by nrshapiro** [comment]
@lhorne-gavant 
Just a progress report:  Tested the **run-current-update.txt** version and it worked well!  Kudos!

Will test the others as the opportunity / need arises.

**Comment by nrshapiro** [comment]
@lhorne-gavant 
Tested **run-full-update** which should produce a data update of all changed documents (archive and current) but not rebuild with latest Solr schema, and it appeared to work (appeared since I didn't have a particular change record to double check, but I do think it worked)

**Comment by lhorne-gavant** [comment]
@nrshapiro 
Glad to hear that Neil! I checked the logs to confirm that data loaders were run for archive and current directories and that there was no solr schema update.

**Comment by nrshapiro** [comment]
@lhorne-gavant 

Leyla, question: for the FILE_GO_LIVE (Push Stage to Production) are you pushing data, software, or both?

**Comment by lhorne-gavant** [comment]
@nrshapiro that deploys the same mysql and solr snapshots running on staging to production. It does not deploy software.

**Comment by nrshapiro** [comment]
@lhorne-gavant  Perfect.
