### ISSUE TITLE
Document matching

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#95]
@nrshapiro 
I am trying to match to document and book information downloaded via your API to get information needed for my counter reports. I can't seem to find a match for the following. Is this because I haven't downloaded correctly or because they are missing?
ADPSAxx.001.0027A
AIM.001.0027A
IJP.001.0027A
IJP.100.0000A
IJP.101.0013A
IJP.101.0923A
PSAR.100.0001A
PSAR.102.0588A
PSAR.102.0683A
PSAR.102.0755A
PSAR.107.0489A
ZBK.049.0001A

PS: I don't seem to be able to assign or label this issue!

**Comment by nrshapiro** [comment]
These don't exist--there's a pattern here...they are all 0027.  And no 
such journal code as ADPSAxx.

You can copy each of the codes into smart search and you'll see they 
don't exist.

IJP.001.0027A
ADPSAxx.001.0027A
AIM.001.0027A
IJP.001.0027A

Doesn't exist: (journals never have a 0000 page (books might)

IJP.100.0000A

These DO exist and can be retrieved by below or pasting the articleID 
into smartsearch as these links show:

IJP.101.0013A https://stage.pep-web.rocks/search?q=IJP.101.0013A
IJP.101.0923A https://stage.pep-web.rocks/search?q=IJP.101.0923A
PSAR.100.0001A https://stage.pep-web.rocks/search?q=PSAR.100.0001A
PSAR.102.0588A https://stage.pep-web.rocks/search?q=PSAR.102.0588A
PSAR.102.0683A https://stage.pep-web.rocks/search?q=PSAR.102.0683A
PSAR.102.0755A https://stage.pep-web.rocks/search?q=PSAR.102.0755A
PSAR.107.0489A https://stage.pep-web.rocks/search?q=PSAR.107.0489A
ZBK.049.0001A https://stage.pep-web.rocks/search?q=ZBK.049.0001A


------ Original Message ------

**Comment by nrshapiro** [comment]
A note of caution, if this is throwing you: the data will not be in sync between stage and production...as it will not be in practice either.

**Comment by jwoosnam** [comment]
@nrshapiro 
I am sorry about the first few codes I now realise that these are intentionally invalid codes from my test scripts.
 
The IJP and PSAR are interesting because the reason I don't have these docs is because when I run: https://stage-api.pep-web.rocks/v2/Metadata/Volumes/ the most recent volumes are not returned, therefore I don't ask for documents for say IJP 101.

**Comment by nrshapiro** [comment]
I wasn't setting a facet limit (used to get years from actual data), because I assumed Solr wouldn't limit something used for analysis, but that's not true.  You need to set a limit, or they set it for you.  The maximum number of facets  is apparently defaulted to 100, and these particular codes have more than that.  

So I set it to 1000.  We shouldn't get there for at least 880 years.

Fixed in Opas Version 2021.0308.1.Alpha.
